name: Check & fix styling (prettier)

on:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run prettier
        uses: permafrost-dev/prettier-docker-ga@main
        with:
          args: --config prettier.config.js .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling D