name: Check & fix styling (prettier)

on:
  push:

jobs:
  actiounlint:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: actionlint
        uses: raven-actions/actionlint@v2


